### ISSUE TITLE
keyboard/mouse input not working on "replay narration"

### ISSUE THREAD

**Issue by sydechen** [mcay23/COMP580HauntedHouse#1]
Hi guys, this is a really fun project! One issue I had when playing the game was that trying to hit the "Replay Narration" button using the keyboard or mouse click doesn't work for me like the other buttons do. I also suggest to play each choice out loud when it is selected by keyboard so that it is easy to know which choice we are on before pressing Enter.

**Comment by mcay23** [comment]
Hi, thanks for the input. We're going to fix this ASAP.

**Comment by mcay23** [comment]
resolved
